import Hero from '@/containers/home/Hero'
import History from '@/containers/home/History'
import Life from '@/containers/home/Life'
import JoinUs from '@/containers/home/JoinUs'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'

export const metadata = {
  title: 'Belvedera School',
  description: 'Generated by create next app',
}

export default function Home() {
  return(
    <>
      <Navbar />
      <Hero />
      <History />
      <Life />
      <JoinUs />
      <Footer />
    </>
  )
}
